# -*- coding: utf-8 -*-
"""基座测试：`platform/identity.py` —— P1 身份凭证（HMAC 签发 / 校验 / 统一准入）。

**为什么算"基层"**：这是平台唯一的**来源身份**机制。注册时签发、
后续消息头携带，是审计可溯源的根；三个挂接点（harness_common 的准入闸门、
消息/任务路由等）共用 `check_request_token` 这一个入口 —— 它一旦漂移，
鉴权就是**三处各自为政**。此前零测试。

安全边界（本文件重点锁死）：
- 常数时间比较（防时序侧信道）—— `hmac.compare_digest`，不得退化成 `==`；
- **向后兼容**：未签发 token 的存量旧 harness 一律放行，不能因为加鉴权而
  把既有桥全打死（这是设计文档明写的约束，误伤 = 线上事故）；
- 缺头 401 / 校验失败 403 不可混用（前端与排障都靠这个区分）。
"""
from __future__ import annotations

import pytest

from agent_community.platform import identity as ident


class Headers(dict):
    """大小写不敏感的 headers（模拟 FastAPI/Starlette 的 `request.headers`）。"""

    def get(self, key, default=None):
        want = str(key).lower()
        for k, v in self.items():
            if str(k).lower() == want:
                return v
        return default


@pytest.fixture()
def fake_config(monkeypatch):
    """把 identity 的配置读写换成内存字典，绝不落盘到 ~/.agent_community。"""
    store: dict = {}

    def _load():
        return dict(store)

    def _save(cfg):
        store.clear()
        store.update(cfg)

    monkeypatch.setattr(ident, "load_config", _load, raising=True)
    monkeypatch.setattr(ident, "save_config", _save, raising=True)
    return store


# ══════════════════════════════════════════════════════════════════
# 签发
# ══════════════════════════════════════════════════════════════════
class TestIssue:
    def test_token_is_sha256_hex(self, fake_config):
        tok = ident.issue_agent_token("harness-A")
        assert len(tok) == 64, "HMAC-SHA256 hex 应为 64 字符"
        assert all(c in "0123456789abcdef" for c in tok), "应为小写 hex"

    def test_same_input_is_stable(self, fake_config):
        """同一 harness + 同一密钥必须可重复验证（否则校验永远失败）。"""
        a = ident.issue_agent_token("harness-A")
        b = ident.issue_agent_token("harness-A")
        assert a == b

    def test_different_harness_differs(self, fake_config):
        assert ident.issue_agent_token("harness-A") != ident.issue_agent_token("harness-B")

    def test_secret_autogenerated_and_persisted(self, fake_config):
        """首次签发应生成密钥并**持久化**；否则重启后旧 token 全部失效。"""
        assert "agent_token_secret" not in fake_config
        ident.issue_agent_token("h1")
        secret = fake_config.get("agent_token_secret")
        assert secret and len(secret) == 64, "应生成 32 字节 hex 密钥"

    def test_secret_is_reused_across_calls(self, fake_config):
        ident.issue_agent_token("h1")
        first = fake_config["agent_token_secret"]
        ident.issue_agent_token("h2")
        assert fake_config["agent_token_secret"] == first, "已有密钥不得被覆盖"

    def test_existing_secret_is_honoured(self, fake_config):
        fake_config["agent_token_secret"] = "f" * 64
        tok = ident.issue_agent_token("h1")
        # 用固定密钥重算，验证确实用了配置里的那个
        import hashlib
        import hmac as _hmac
        expected = _hmac.new(("f" * 64).encode(), b"h1", hashlib.sha256).hexdigest()
        assert tok == expected

    def test_save_failure_does_not_break_issue(self, fake_config, monkeypatch):
        """写盘失败不阻断：进程内仍要能签发（设计约束）。"""
        def boom(_cfg):
            raise OSError("disk full")

        monkeypatch.setattr(ident, "save_config", boom, raising=True)
        tok = ident.issue_agent_token("h1")
        assert len(tok) == 64


# ══════════════════════════════════════════════════════════════════
# 校验
# ══════════════════════════════════════════════════════════════════
class TestVerify:
    def test_correct_token_accepted(self, fake_config):
        tok = ident.issue_agent_token("harness-A")
        assert ident.verify_agent_token("harness-A", tok) is True

    def test_wrong_token_rejected(self, fake_config):
        ident.issue_agent_token("harness-A")
        assert ident.verify_agent_token("harness-A", "0" * 64) is False

    def test_token_bound_to_harness_id(self, fake_config):
        """拿 A 的 token 冒充 B 必须失败 —— token 是与 harness_id 绑定的。"""
        tok_a = ident.issue_agent_token("harness-A")
        assert ident.verify_agent_token("harness-B", tok_a) is False

    def test_empty_token_rejected(self, fake_config):
        assert ident.verify_agent_token("harness-A", "") is False
        assert ident.verify_agent_token("harness-A", None) is False

    def test_tampered_token_rejected(self, fake_config):
        tok = ident.issue_agent_token("harness-A")
        tampered = ("b" if tok[0] != "b" else "c") + tok[1:]
        assert ident.verify_agent_token("harness-A", tampered) is False


# ══════════════════════════════════════════════════════════════════
# 取头 / 是否已签发
# ══════════════════════════════════════════════════════════════════
class TestHeaderExtraction:
    def test_header_name_constant(self):
        assert ident.AGENT_TOKEN_HEADER == "x-agent-token"

    def test_extracts_lowercase(self):
        assert ident.extract_token_from_headers({"x-agent-token": "abc"}) == "abc"

    def test_case_insensitive_via_fastapi_headers(self):
        """真实调用方传的是 FastAPI Headers（大小写不敏感）。"""
        assert ident.extract_token_from_headers(
            Headers({"X-Agent-Token": "abc"})) == "abc"

    def test_missing_returns_empty(self):
        assert ident.extract_token_from_headers({}) == ""
        assert ident.extract_token_from_headers(Headers({})) == ""

    def test_strips_whitespace(self):
        assert ident.extract_token_from_headers({"x-agent-token": "  abc  "}) == "abc"


class TestHasAgentToken:
    def test_false_for_empty(self):
        assert ident.has_agent_token({}) is False
        assert ident.has_agent_token(None) is False

    def test_true_when_present(self):
        assert ident.has_agent_token({"agent_token": "x"}) is True

    def test_blank_token_is_false(self):
        """空串等于没签发 —— 否则会要求一个永远给不出的凭证。"""
        assert ident.has_agent_token({"agent_token": ""}) is False


# ══════════════════════════════════════════════════════════════════
# 统一准入入口
# ══════════════════════════════════════════════════════════════════
class TestCheckRequestToken:
    def test_no_harness_id_passes(self, fake_config):
        assert ident.check_request_token("", {"agent_token": "x"}, {}) is None

    def test_legacy_harness_without_token_passes(self, fake_config):
        """向后兼容红线：未签发 token 的存量 harness 一律放行。"""
        assert ident.check_request_token("h-legacy", {}, {}) is None
        assert ident.check_request_token("h-legacy", None, {}) is None

    def test_missing_header_is_401(self, fake_config):
        ident.issue_agent_token("h1")
        verdict = ident.check_request_token(
            "h1", {"agent_token": "issued"}, Headers({}))
        assert verdict is not None
        assert verdict[0] == 401, "缺凭证应与校验失败区分（401）"
        assert "x-agent-token" in verdict[1]

    def test_wrong_token_is_403(self, fake_config):
        ident.issue_agent_token("h1")
        verdict = ident.check_request_token(
            "h1", {"agent_token": "issued"}, Headers({"X-Agent-Token": "0" * 64}))
        assert verdict is not None
        assert verdict[0] == 403, "凭证错误应为 403"

    def test_correct_token_passes(self, fake_config):
        tok = ident.issue_agent_token("h1")
        assert ident.check_request_token(
            "h1", {"agent_token": "issued"}, Headers({"X-Agent-Token": tok})) is None

    def test_uses_constant_time_compare(self):
        """防时序侧信道：必须走 hmac.compare_digest，不得是裸 `==`。"""
        import inspect

        src = inspect.getsource(ident.verify_agent_token)
        assert "compare_digest" in src, (
            "verify_agent_token 必须使用 hmac.compare_digest（常数时间），"
            "退化成正则/== 比较会引入时序侧信道"
        )
