# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import agent_community_pb2 as agent__community__pb2

GRPC_GENERATED_VERSION = '1.84.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in agent_community_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class AgentCommunityStub:
    """信封式设计：payload_json 承载复杂业务结构，与 HTTP 接口零协议漂移
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RegisterHarness = channel.unary_unary(
                '/agent_community.v1.AgentCommunity/RegisterHarness',
                request_serializer=agent__community__pb2.RegisterRequest.SerializeToString,
                response_deserializer=agent__community__pb2.RegisterReply.FromString,
                _registered_method=True)
        self.SendMessage = channel.unary_unary(
                '/agent_community.v1.AgentCommunity/SendMessage',
                request_serializer=agent__community__pb2.HarnessMessage.SerializeToString,
                response_deserializer=agent__community__pb2.MessageAck.FromString,
                _registered_method=True)
        self.SubmitTask = channel.unary_unary(
                '/agent_community.v1.AgentCommunity/SubmitTask',
                request_serializer=agent__community__pb2.SubmitTaskRequest.SerializeToString,
                response_deserializer=agent__community__pb2.TaskAck.FromString,
                _registered_method=True)
        self.GetTask = channel.unary_unary(
                '/agent_community.v1.AgentCommunity/GetTask',
                request_serializer=agent__community__pb2.GetTaskRequest.SerializeToString,
                response_deserializer=agent__community__pb2.TaskStatus.FromString,
                _registered_method=True)
        self.ReportResult = channel.unary_unary(
                '/agent_community.v1.AgentCommunity/ReportResult',
                request_serializer=agent__community__pb2.TaskResult.SerializeToString,
                response_deserializer=agent__community__pb2.ResultAck.FromString,
                _registered_method=True)
        self.ListProtocols = channel.unary_unary(
                '/agent_community.v1.AgentCommunity/ListProtocols',
                request_serializer=agent__community__pb2.ProtocolsRequest.SerializeToString,
                response_deserializer=agent__community__pb2.ProtocolsReply.FromString,
                _registered_method=True)


class AgentCommunityServicer:
    """信封式设计：payload_json 承载复杂业务结构，与 HTTP 接口零协议漂移
    """

    def RegisterHarness(self, request, context):
        """注册 harness（等价 POST /api/harness/register）
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SendMessage(self, request, context):
        """消息入站（带 agent-token，走 P1 身份校验）
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SubmitTask(self, request, context):
        """任务派发
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetTask(self, request, context):
        """任务状态查询
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReportResult(self, request, context):
        """结果回报（等价 POST /api/harness/task-result）
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListProtocols(self, request, context):
        """列出协议目录（等价 GET /api/protocols）
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AgentCommunityServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RegisterHarness': grpc.unary_unary_rpc_method_handler(
                    servicer.RegisterHarness,
                    request_deserializer=agent__community__pb2.RegisterRequest.FromString,
                    response_serializer=agent__community__pb2.RegisterReply.SerializeToString,
            ),
            'SendMessage': grpc.unary_unary_rpc_method_handler(
                    servicer.SendMessage,
                    request_deserializer=agent__community__pb2.HarnessMessage.FromString,
                    response_serializer=agent__community__pb2.MessageAck.SerializeToString,
            ),
            'SubmitTask': grpc.unary_unary_rpc_method_handler(
                    servicer.SubmitTask,
                    request_deserializer=agent__community__pb2.SubmitTaskRequest.FromString,
                    response_serializer=agent__community__pb2.TaskAck.SerializeToString,
            ),
            'GetTask': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTask,
                    request_deserializer=agent__community__pb2.GetTaskRequest.FromString,
                    response_serializer=agent__community__pb2.TaskStatus.SerializeToString,
            ),
            'ReportResult': grpc.unary_unary_rpc_method_handler(
                    servicer.ReportResult,
                    request_deserializer=agent__community__pb2.TaskResult.FromString,
                    response_serializer=agent__community__pb2.ResultAck.SerializeToString,
            ),
            'ListProtocols': grpc.unary_unary_rpc_method_handler(
                    servicer.ListProtocols,
                    request_deserializer=agent__community__pb2.ProtocolsRequest.FromString,
                    response_serializer=agent__community__pb2.ProtocolsReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'agent_community.v1.AgentCommunity', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('agent_community.v1.AgentCommunity', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AgentCommunity:
    """信封式设计：payload_json 承载复杂业务结构，与 HTTP 接口零协议漂移
    """

    @staticmethod
    def RegisterHarness(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/agent_community.v1.AgentCommunity/RegisterHarness',
            agent__community__pb2.RegisterRequest.SerializeToString,
            agent__community__pb2.RegisterReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SendMessage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/agent_community.v1.AgentCommunity/SendMessage',
            agent__community__pb2.HarnessMessage.SerializeToString,
            agent__community__pb2.MessageAck.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SubmitTask(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/agent_community.v1.AgentCommunity/SubmitTask',
            agent__community__pb2.SubmitTaskRequest.SerializeToString,
            agent__community__pb2.TaskAck.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetTask(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/agent_community.v1.AgentCommunity/GetTask',
            agent__community__pb2.GetTaskRequest.SerializeToString,
            agent__community__pb2.TaskStatus.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReportResult(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/agent_community.v1.AgentCommunity/ReportResult',
            agent__community__pb2.TaskResult.SerializeToString,
            agent__community__pb2.ResultAck.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListProtocols(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/agent_community.v1.AgentCommunity/ListProtocols',
            agent__community__pb2.ProtocolsRequest.SerializeToString,
            agent__community__pb2.ProtocolsReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
